# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


State.destroy_all

State.create([
{name:'Alabama',lat:32.806671,long:-86.791130,grow:false, grow_details:"In hac habitasse platea dictumst. Etiam faucibus cursus urna.",possess:true,possess_details:"Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",carry_limit:"Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",buy_or_sell:true,buy_or_sell_details:"Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo."},
{name:'Alaska',lat:61.370716,long:-152.404419,grow:false, grow_details:"In hac habitasse platea dictumst.",possess:true,possess_details:"In hac habitasse platea dictumst.",carry_limit:"Vivamus tortor.",buy_or_sell:true,buy_or_sell_details:"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla."},
{name:'Arizona',lat:33.729759,long:-111.431221,grow:false, grow_details:"Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",possess:true,possess_details:"Pellentesque at nulla. Suspendisse potenti.",carry_limit:"Donec semper sapien a libero.",buy_or_sell:true,buy_or_sell_details:"Pellentesque at nulla. Suspendisse potenti."},
{name:'Arkansas',lat:34.969704,long:-92.373123,grow:false, grow_details:"Ut tellus.",possess:true,possess_details:"In hac habitasse platea dictumst.",carry_limit:"Phasellus sit amet erat.",buy_or_sell:false,buy_or_sell_details:"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat."},
{name:'California',lat:36.116203,long:-119.681564,grow:false, grow_details:"Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.",possess:false,possess_details:"Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",carry_limit:"Suspendisse potenti.",buy_or_sell:true,buy_or_sell_details:"In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit."},
{name:'Colorado',lat:39.059811,long:-105.311104,grow:false, grow_details:"In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.",possess:true,possess_details:"In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",carry_limit:"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",buy_or_sell:true,buy_or_sell_details:"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa."},
{name:'Connecticut',lat:41.597782,long:-72.755371,grow:false, grow_details:"Morbi a ipsum.",possess:false,possess_details:"Donec semper sapien a libero.",carry_limit:"Sed vel enim sit amet nunc viverra dapibus.",buy_or_sell:true,buy_or_sell_details:"Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede."},
{name:'Delaware',lat:39.318523,long:-75.507141,grow:false, grow_details:"Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.",possess:true,possess_details:"Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",carry_limit:"Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",buy_or_sell:true,buy_or_sell_details:"Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci."},
{name:'District of Columbia',lat:38.897438,long:-77.026817,grow:false, grow_details:"Nulla suscipit ligula in lacus.",possess:false,possess_details:"Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",carry_limit:"Proin eu mi. Nulla ac enim.",buy_or_sell:false,buy_or_sell_details:"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis."},
{name:'Florida',lat:27.766279,long:-81.686783,grow:true, grow_details:"Vestibulum ac est lacinia nisi venenatis tristique.",possess:true,possess_details:"Duis ac nibh.",carry_limit:"Duis aliquam convallis nunc.",buy_or_sell:true,buy_or_sell_details:"Vestibulum sed magna at nunc commodo placerat. Praesent blandit."},
{name:'Georgia',lat:33.040619,long:-83.643074,grow:false, grow_details:"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.",possess:true,possess_details:"Suspendisse potenti.",carry_limit:"Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",buy_or_sell:true,buy_or_sell_details:"Donec posuere metus vitae ipsum. Aliquam non mauris."},
{name:'Hawaii',lat:21.094318,long:-157.498337,grow:true, grow_details:"Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.",possess:false,possess_details:"Nulla tempus.",carry_limit:"Morbi a ipsum.",buy_or_sell:true,buy_or_sell_details:"In eleifend quam a odio. In hac habitasse platea dictumst."},
{name:'Idaho',lat:44.240459,long:-114.478828,grow:false, grow_details:"Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.",possess:false,possess_details:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.",carry_limit:"Duis aliquam convallis nunc.",buy_or_sell:false,buy_or_sell_details:"Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam."},
{name:'Illinois',lat:40.349457,long:-88.986137,grow:true, grow_details:"Donec dapibus.",possess:true,possess_details:"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",carry_limit:"Maecenas ut massa quis augue luctus tincidunt.",buy_or_sell:false,buy_or_sell_details:"Suspendisse potenti. In eleifend quam a odio."},
{name:'Indiana',lat:39.849426,long:-86.258278,grow:false, grow_details:"Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.",possess:true,possess_details:"Aliquam quis turpis eget elit sodales scelerisque.",carry_limit:"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",buy_or_sell:false,buy_or_sell_details:"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque."},
{name:'Iowa',lat:42.011539,long:-93.210526,grow:true, grow_details:"Curabitur in libero ut massa volutpat convallis.",possess:false,possess_details:"Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.",carry_limit:"Nunc nisl.",buy_or_sell:true,buy_or_sell_details:"Donec vitae nisi."},
{name:'Kansas',lat:38.526600,long:-96.726486,grow:false, grow_details:"In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",possess:true,possess_details:"Nullam molestie nibh in lectus. Pellentesque at nulla.",carry_limit:"Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.",buy_or_sell:false,buy_or_sell_details:"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit."},
{name:'Kentucky',lat:37.668140,long:-84.670067,grow:false, grow_details:"Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.",possess:false,possess_details:"Aenean sit amet justo.",carry_limit:"Nulla ac enim.",buy_or_sell:false,buy_or_sell_details:"Cras non velit nec nisi vulputate nonummy."},
{name:'Louisiana',lat:31.169546,long:-91.867805,grow:false, grow_details:"Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",possess:true,possess_details:"Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",carry_limit:"Nulla facilisi.",buy_or_sell:true,buy_or_sell_details:"Maecenas ut massa quis augue luctus tincidunt."},
{name:'Maine',lat:44.693947,long:-69.381927,grow:true, grow_details:"In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",possess:false,possess_details:"Ut tellus.",carry_limit:"Donec semper sapien a libero.",buy_or_sell:true,buy_or_sell_details:"Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam."},
{name:'Maryland',lat:39.063946,long:-76.802101,grow:true, grow_details:"Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.",possess:false,possess_details:"Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.",carry_limit:"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",buy_or_sell:false,buy_or_sell_details:"Aenean sit amet justo. Morbi ut odio."},
{name:'Massachusetts',lat:42.230171,long:-71.530106,grow:true, grow_details:"Integer tincidunt ante vel ipsum.",possess:false,possess_details:"Cras pellentesque volutpat dui.",carry_limit:"Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",buy_or_sell:true,buy_or_sell_details:"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti."},
{name:'Michigan',lat:43.326618,long:-84.536095,grow:false, grow_details:"Suspendisse ornare consequat lectus.",possess:false,possess_details:"Duis at velit eu est congue elementum.",carry_limit:"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.",buy_or_sell:true,buy_or_sell_details:"Suspendisse accumsan tortor quis turpis. Sed ante."},
{name:'Minnesota',lat:45.694454,long:-93.900192,grow:false, grow_details:"Integer ac neque.",possess:false,possess_details:"In quis justo.",carry_limit:"Phasellus id sapien in sapien iaculis congue.",buy_or_sell:false,buy_or_sell_details:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus."},
{name:'Mississippi',lat:32.741646,long:-89.678696,grow:false, grow_details:"Suspendisse potenti. In eleifend quam a odio.",possess:true,possess_details:"Duis aliquam convallis nunc.",carry_limit:"Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",buy_or_sell:false,buy_or_sell_details:"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros."},
{name:'Missouri',lat:38.456085,long:-92.288368,grow:false, grow_details:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.",possess:true,possess_details:"Nullam varius. Nulla facilisi.",carry_limit:"Donec dapibus.",buy_or_sell:true,buy_or_sell_details:"Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue."},
{name:'Montana',lat:46.921925,long:-110.454353,grow:true, grow_details:"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.",possess:false,possess_details:"Aliquam sit amet diam in magna bibendum imperdiet.",carry_limit:"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",buy_or_sell:false,buy_or_sell_details:"Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue."},
{name:'Nebraska',lat:41.125370,long:-98.268082,grow:true, grow_details:"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",possess:false,possess_details:"Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.",carry_limit:"Proin risus. Praesent lectus.",buy_or_sell:true,buy_or_sell_details:"Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam."},
{name:'Nevada',lat:38.313515,long:-117.055374,grow:true, grow_details:"Quisque id justo sit amet sapien dignissim vestibulum.",possess:true,possess_details:"Nunc rhoncus dui vel sem. Sed sagittis.",carry_limit:"Nunc purus.",buy_or_sell:false,buy_or_sell_details:"In sagittis dui vel nisl. Duis ac nibh."},
{name:'New Hampshire',lat:43.452492,long:-71.563896,grow:false, grow_details:"In hac habitasse platea dictumst.",possess:false,possess_details:"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",carry_limit:"Suspendisse potenti. In eleifend quam a odio.",buy_or_sell:true,buy_or_sell_details:"Suspendisse potenti."},
{name:'New Jersey',lat:40.298904,long:-74.521011,grow:true, grow_details:"Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",possess:false,possess_details:"Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",carry_limit:"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.",buy_or_sell:false,buy_or_sell_details:"Integer a nibh."},
{name:'New Mexico',lat:34.840515,long:-106.248482, grow:true, grow_details:"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.",possess:false,possess_details:"Morbi non quam nec dui luctus rutrum.",carry_limit:"Nullam molestie nibh in lectus. Pellentesque at nulla.",buy_or_sell:false,buy_or_sell_details:"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien."},
{name:'New York',lat:42.165726,long:-74.948051, grow:false, grow_details:"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",possess:true,possess_details:"Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.",carry_limit:"Sed sagittis.",buy_or_sell:true,buy_or_sell_details:"Cras pellentesque volutpat dui."},
{name:'North Carolina',lat:35.630066,long:-79.806419, grow:true, grow_details:"Nullam varius. Nulla facilisi.",possess:true,possess_details:"Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",carry_limit:"Nullam varius.",buy_or_sell:true,buy_or_sell_details:"Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla."},
{name:'North Dakota',lat:47.528912,long:-99.784012, grow:true, grow_details:"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.",possess:false,possess_details:"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",carry_limit:"Fusce consequat. Nulla nisl.",buy_or_sell:true,buy_or_sell_details:"Curabitur convallis."},
{name:'Ohio',lat:40.388783,long:-82.764915, grow:true, grow_details:"Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",possess:true,possess_details:"Nulla nisl.",carry_limit:"Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",buy_or_sell:false,buy_or_sell_details:"Nulla suscipit ligula in lacus."},
{name:'Oklahoma',lat:35.565342,long:-96.928917, grow:false, grow_details:"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.",possess:false,possess_details:"Cras non velit nec nisi vulputate nonummy.",carry_limit:"Pellentesque viverra pede ac diam.",buy_or_sell:true,buy_or_sell_details:"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue."},
{name:'Oregon',lat:44.572021,long:-122.070938, grow:false, grow_details:"Etiam pretium iaculis justo. In hac habitasse platea dictumst.",possess:true,possess_details:"Aenean sit amet justo. Morbi ut odio.",carry_limit:"Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",buy_or_sell:true,buy_or_sell_details:"Cras non velit nec nisi vulputate nonummy."},
{name:'Pennsylvania',lat:40.590752,long:-77.209755, grow:false, grow_details:"Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",possess:false,possess_details:"In congue. Etiam justo.",carry_limit:"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.",buy_or_sell:false,buy_or_sell_details:"Donec dapibus."},
{name:'Rhode Island',lat:41.680893,long:-71.511780, grow:false, grow_details:"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.",possess:true,possess_details:"Donec dapibus. Duis at velit eu est congue elementum.",carry_limit:"Nullam varius. Nulla facilisi.",buy_or_sell:false,buy_or_sell_details:"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam."},
{name:'South Carolina',lat:33.856892,long:-80.945007, grow:false, grow_details:"Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",possess:true,possess_details:"Duis bibendum.",carry_limit:"Ut at dolor quis odio consequat varius. Integer ac leo.",buy_or_sell:true,buy_or_sell_details:"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci."},
{name:'South Dakota',lat:44.299782,long:-99.438828, grow:true, grow_details:"Nullam molestie nibh in lectus.",possess:true,possess_details:"Vestibulum sed magna at nunc commodo placerat.",carry_limit:"Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.",buy_or_sell:true,buy_or_sell_details:"Suspendisse potenti."},
{name:'Tennessee',lat:35.747845,long:-86.692345, grow:true, grow_details:"In quis justo. Maecenas rhoncus aliquam lacus.",possess:true,possess_details:"Integer non velit.",carry_limit:"Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.",buy_or_sell:false,buy_or_sell_details:"Duis mattis egestas metus. Aenean fermentum."},
{name:'Texas',lat:31.054487,long:-97.563461, grow:false, grow_details:"Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",possess:false,possess_details:"Proin eu mi.",carry_limit:"Curabitur gravida nisi at nibh.",buy_or_sell:true,buy_or_sell_details:"In hac habitasse platea dictumst. Etiam faucibus cursus urna."},
{name:'Utah',lat:40.150032,long:-111.862434, grow:true, grow_details:"Integer ac neque. Duis bibendum.",possess:false,possess_details:"Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",carry_limit:"In congue. Etiam justo.",buy_or_sell:true,buy_or_sell_details:"Nulla facilisi. Cras non velit nec nisi vulputate nonummy."},
{name:'Vermont',lat:44.045876,long:-72.710686, grow:true, grow_details:"Nulla nisl.",possess:false,possess_details:"Integer a nibh. In quis justo.",carry_limit:"Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",buy_or_sell:false,buy_or_sell_details:"Aliquam non mauris. Morbi non lectus."},
{name:'Virginia',lat:37.769337,long:-78.169968, grow:false, grow_details:"Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",possess:false,possess_details:"Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",carry_limit:"Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",buy_or_sell:true,buy_or_sell_details:"Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum."},
{name:'Washington',lat:47.400902,long:-121.490494, grow:true, grow_details:"Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",possess:true,possess_details:"Aliquam sit amet diam in magna bibendum imperdiet.",carry_limit:"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.",buy_or_sell:false,buy_or_sell_details:"Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis."},
{name:'West Virginia',lat:38.491226,long:-80.954453, grow:true, grow_details:"Nullam molestie nibh in lectus.",possess:false,possess_details:"Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",carry_limit:"In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",buy_or_sell:true,buy_or_sell_details:"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue."},
{name:'Wisconsin',lat:44.268543,long:-89.616508, grow:false, grow_details:"Phasellus sit amet erat. Nulla tempus.",possess:true,possess_details:"Nulla ut erat id mauris vulputate elementum. Nullam varius.",carry_limit:"Morbi vel lectus in quam fringilla rhoncus.",buy_or_sell:true,buy_or_sell_details:"Suspendisse ornare consequat lectus."},
{name:'Wyoming',lat:42.755966,long:-107.302490, grow:false, grow_details:"Phasellus sit amet erat. Nulla tempus.",possess:true,possess_details:"Nulla ut erat id mauris vulputate elementum. Nullam varius.",carry_limit:"Morbi vel lectus in quam fringilla rhoncus.",buy_or_sell:true,buy_or_sell_details:"Suspendisse ornare consequat lectus."}

])
