# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

State.destroy_all

State.create([

{name:"Alabama",lat:32.806671,long:-86.79113,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Alaska",lat:61.2167,long:-149.9000,possession:"legal",possession_details:"Adults 21+ can possess up to 2 oz of marijuana",paraphernalia:"legal",paraphernalia_details:"Adults 18+ can possess and buy marijuana paraphernalia",consumption:"caution",consumption_details:"Public consumption of marijuana is illegal (home use permitted)",growing:"legal",growing_details:"Adults 21+ can grow up to 6 plants on home property",medical:"legal",medical_details:"Qualifying patients can buy up to 2 oz of marijuana from a registered dispensary",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Arizona",lat:33.729759,long:-111.431221,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Arkansas",lat:34.969704,long:-92.373123,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"California",lat:36.116203,long:-119.681564,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Colorado",lat:39.059811,long:-105.311104,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Connecticut",lat:41.597782,long:-72.755371,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Delaware",lat:39.318523,long:-75.507141,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"District of Columbia",lat:38.897438,long:-77.026817,possession:"legal",possession_details:"Adults 21+ can possess up to 2 oz of marijuana",paraphernalia:"legal",paraphernalia_details:"Adults 18+ can possess and buy marijuana paraphernalia",consumption:"caution",consumption_details:"Public consumption of marijuana is illegal (home use permitted)",growing:"legal",growing_details:"Adults 21+ can grow up to 6 plants on home property",medical:"legal",medical_details:"Qualifying patients can buy up to 2 oz of marijuana from a registered dispensary",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Florida",lat:27.766279,long:-81.686783,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Georgia",lat:33.040619,long:-83.643074,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Hawaii",lat:21.094318,long:-157.498337,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Idaho",lat:44.240459,long:-114.478828,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Illinois",lat:40.349457,long:-88.986137,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Indiana",lat:39.849426,long:-86.258278,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Iowa",lat:42.011539,long:-93.210526,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Kansas",lat:38.5266,long:-96.726486,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Kentucky",lat:37.66814,long:-84.670067,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Louisiana",lat:31.169546,long:-91.867805,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Maine",lat:44.693947,long:-69.381927,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Maryland",lat:39.063946,long:-76.802101,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Massachusetts",lat:42.230171,long:-71.530106,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Michigan",lat:43.326618,long:-84.536095,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Minnesota",lat:45.694454,long:-93.900192,possession:"caution",possession_details:"Possession of up to 42.5 g of marijuana is a decriminalized civil offense",paraphernalia:"caution",paraphernalia_details:"Possession of marijuana paraphernalia is a decriminalized civil offense",consumption:"illegal",consumption_details:"Recreational consumption of marijuana is illegal",growing:"caution",growing_details:"Growing up to 42.5 g of marijuana is a decriminalized civil offense",medical:"legal",medical_details:"Qualifying patients can buy a 30 day supply of marijuana edibles from a registered dispensary",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Mississippi",lat:32.741646,long:-89.678696,possession:"caution",possession_details:"Possession of up to 30 g of marijuana is a decriminalized civil offense for first time offenders",paraphernalia:"illegal",paraphernalia_details:"Possession of marijuana paraphernalia is illegal",consumption:"illegal",consumption_details:"Recreational consumption of marijuana is illegal",growing:"caution",growing_details:"Growing up to 30 oz of marijuana is a decriminalized civil offense for first time offenders",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Missouri",lat:38.456085,long:-92.288368,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Montana",lat:46.921925,long:-110.454353,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Nebraska",lat:41.12537,long:-98.268082,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Nevada",lat:36.1215,long:-115.1739,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"New Hampshire",lat:43.452492,long:-71.563896,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"New Jersey",lat:40.298904,long:-74.521011,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"New Mexico",lat:35.6672,long:-105.9644,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"New York",lat:42.165726,long:-74.948051,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"North Carolina",lat:35.630066,long:-79.806419,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"North Dakota",lat:47.528912,long:-99.784012,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Ohio",lat:40.388783,long:-82.764915,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Oklahoma",lat:35.565342,long:-96.928917,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Oregon",lat:45.52,long:-122.6819,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Pennsylvania",lat:40.590752,long:-77.209755,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Rhode Island",lat:41.680893,long:-71.51178,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"South Carolina",lat:33.856892,long:-80.945007,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"South Dakota",lat:44.299782,long:-99.438828,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Tennessee",lat:35.747845,long:-86.692345,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Texas",lat:31.054487,long:-97.563461,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Utah",lat:40.150032,long:-111.862434,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Vermont",lat:44.045876,long:-72.710686,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Virginia",lat:37.769337,long:-78.169968,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Washington",lat:47.400902,long:-121.490494,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"West Virginia",lat:38.491226,long:-80.954453,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Wisconsin",lat:44.268543,long:-89.616508,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"},

{name:"Wyoming",lat:42.755966,long:-107.30249,possession:"illegal",possession_details:"It is illegal to possess any amount of marijuana",paraphernalia:"illegal",paraphernalia_details:"It is illegal to possess and buy marijuana paraphernalia",consumption:"illegal",consumption_details:"It is illegal to consume marijuana in both public and private",growing:"illegal",growing_details:"It is illegal to grow any number of marijuana plants",medical:"illegal",medical_details:"Marijuana is not legalized for medical use",buy_or_sell:"illegal",buy_or_sell_details:"Buying and selling marijuana for recreational use is illegal"}

])